dist: trusty
sudo: required

language: node_js
node_js:
  - "stable"

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  firefox: "latest"

cache:
  directories:
    - "$HOME/node_modules"
    - "$HOME/.npm"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

notifications:
  email:
    on_success: never
    on_failure: change

