language: node_js
node_js:
  - "stable"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "./node_modules/.bin/selenium &"
notifications:
  email:
    on_success: never
    on_failure: change

